FROM httpd:2.4-alpine
COPY build /usr/local/apache2/htdocs/

# FROM nginx:1.19.0-alpine
# COPY build /usr/share/nginx/html
# COPY ./sysmon.conf /etc/nginx/conf.d/
# CMD ["nginx", "-g", "daemon off;"]
# COPY ./nginx.conf /etc/nginx/nginx.conf


# EXPOSE 80
